external-apps/Goodgym

- package.json
- src/server.js
- tests/server.test.js
relates #17 
- add mocha, chai and supertest
- add basic tests for routes
> GG 17 tests

- .gitignore
- README.md
- bin/build-css
- bin/dev-start
- bin/start
- bin/test
- bin/watch-css
- package.json
- public/css/main.css
- scss/main.scss
- src/routes.js
- src/server.js
- src/templates/layout/main.hbs
Fixes #19 
- setup node-sass
- we have decided against Compass.js for now
- refactor package.json with a bin folder for scripts
> Setup sass. Related #19

- .eslintrc.js
- .gitignore
- README.md
- package.json
- public/css/main.css
We are using ESLint standard but we have changed the rule so that semicolons are needed at the end of lines.
> Setup ESLint. Related #21.

- src/database/db-add-run.js
- src/database/db-add-users.js
- src/database/db-connection.js
- src/database/db-find-all.js
Add mongoose and mongodb.
Create 3 files in database folder:
1. db-connection.js
2. db-find-all.js
3. db-add-users.js
> Create database - Related #23

- package.json
- src/database/db-add-run.js
- src/database/db-find-all.js
- src/database/db-find-one.js
related #23  (sorry, I related my commits to incorrect issue 25 instead of 23)
- add *findOneRun* function
- add arrow functions
> GG 25 find one run 

- src/database/db-add-run.js
- src/database/db-connection.js
- src/database/db-driver.js
Related #25 
- create https server
- connect to mLab for hosting database
- npm env2
- create environment variables
> Connect database to hosting platform

- public/index.js
- scss/_home.scss
- scss/_layout.scss
- scss/_login.scss
- scss/main.scss
- src/routes.js
- src/routes/login.js
- src/templates/views/login.hbs
Fixes #41
When 'create task sheet' is clicked on the login page you are directed to the home page with the loginID as a param.
> Create login page

- public/index.js
- scss/_layout.scss
- scss/_qr.scss
- scss/main.scss
- src/templates/views/qr.hbs
- use a MutationObserver function! 
- hide yoti generated qr and replace it with out own using src of the yoti generated one. 
Fixes #43
> Style qr page

- src/database/db-add-run.js
- src/database/db-update-run.js
- src/routes/post-run.js
fixes #39 
relates #34 
- create updateRun function
> GG 39 update run

- public/index.js
- src/routes.js
- src/routes/get-run.js
- src/templates/views/login.hbs
fixes #45 
- add `get-run` route
- get data from database
- fill textareas with data from database
> GG 45 get info from db

- package.json
- public/index.js
- src/routes/getRunFromGoodGym.js
- src/routes/home.js
- src/templates/views/home.hbs
relates #6,
- add request module,
- add get request to goodgym endpoint in order to get run
- update home route
- prefill textareas with data from goodgym endpoint
> GG 6 prefill tasksheet

- README.md
- package.json
- public/index.js
- scss/_home.scss
- src/routes.js
- src/routes/send-email.js
- src/send-email.js
- src/templates/views/email.hbs
- src/templates/views/home.hbs
- add nodemailer
- create goodgym1000@gmail.com for nodemailer
- use handlebars to template email
Fixes #52
> Email QR to Trainer

- src/routes/getRunFromGoodGym.js
- src/templates/views/home.hbs
> Add updated GoodGym JSON API address

- src/routes/post-run.js
- src/routes/send-qr-email.js
- src/routes/send-task-sheet.js
- tests/server.test.js
> Add test for all routes.

- public/scripts/home.js
- src/helpers/get-run-from-goodgym.js
- src/routes/confirmation.js
> Correct bug

- src/helpers/auth-middleware.js
- src/routes.js
fixes #84
- change `successRedirect` to `successReturnToOrRedirect`
- add `req.session.returnTo = req.url;` to `authMiddleware`
> Redirect the user back to the same page after authentication

- public/scripts/confirmation.js
fixes #86
- fix send-email functionality on confirmation page
> Fix send-email on conformation page

- public/scripts/login.js
- public/scripts/task-sheet.js
- src/routes/confirmation.js
- src/routes/enter-run.js
- src/routes/home.js
- src/routes/login.js
- src/routes/qr.js
- src/routes/tasksheet.js
- src/server.js
fixes #91 
- remove global variable user (from `server.js`)
- pass user to routes when we want a logout button to be displayed
- remove unneeded files
> 91 logout button

- public/scripts/confirmation.js
- public/scripts/enterRun.js
- public/scripts/home.js
- public/scripts/index.js
- public/scripts/qr.js
relates #65 
- change `document.getElementsByClassName` to `document.querySelector` in all files inside `scripts` folder
> 65 query selector

- public/scripts/confirmation.js
- public/scripts/home.js
- public/scripts/index.js
- src/routes.js
- src/routes/post-run.js
- src/routes/send-qr-email.js
- src/routes/send-task-sheet.js
related #65
- add common ajax abstraction
hi @eliascodes, this is my attempt of creating a common ajax abstraction.  The `request` function is heavily inspired by your workshop. I am not sure if I correctly handled errors.
> Add common ajax abstraction

- public/scripts/index.js
- scss/_layout.scss
- src/routes/home.js
- src/templates/views/home.hbs
If there is no destination the endpoint will be the same as the start point.
Fixes #99
> Add destination from GoodGym JSON to google maps.

- src/database/db-connection.js
Old account was connected to my email address.
Fixes #106
> Update to new MLab account

- src/routes/qr.js
- src/templates/views/qr.hbs
As reported in #108 the Scenario ID was hardcoded in the view.
Replacing it with the environment variable.
> Removing hardcoded scenario id

- package.json
Due to security vulnerability.
> Upgrade node version

- public/scripts/home.js
- src/routes/home.js
- src/templates/views/home.hbs
We must have changed the API and it broke the way the start location is determined.
> Fix start location
